export type BoqHeader = {
  id: number;
  name: string;
  project_id: number;
  company_name: string;
  client_name: string;
  location: string;
  boq_date: string;
  discount: number;
  total_value: number;
  total_items: number;
  payment_terms: string;
  validity_terms: string;
  warranty: string;
  completion: string;
  exclusion: string;
  terms_and_conditions: string;
  created_on: string;
  project_name: string;
  project_size: string;
  type_of_work: string;
  quoted_budget: string;
  currency: string;
  allocated_budget: string;
  project_start_date: string;
  project_end_date: string;
  project_created_at: string;
  project_currency: string;
  is_draft: boolean;
  is_primary: boolean;
  revision_of: number | null;
};
