import { LPOMrLine } from "./lpoMrLine";
import { LPOJoLine } from "./lpoJoLine";

export type LpoHeader = {
  id: number;
  project_id: number;
  project_name: string;
  mr_header_id: number;
  supplier_id: number | null;
  quotation_code: string;
  supplier_contact_person_name: string;
  supplier_email: string;
  delivery_date: string;
  payment_terms: string;
  delivery_terms: string;
  subtotal: number;
  discount: number;
  vat_rate: number;
  vat: number;
  shipping_and_handling: number;
  total: number;
  payment_status: string;
  payment_reject_status: string;
  invoice_file: string[];
  payment_file: string[];
  signed_file: string[];
  lpo_mr_lines: LPOMrLine[];
  supplier_name: string;
  supplier_address: string;
  supplier_trn_number: string;
  created_at: string;
  date_requested?: string;
  // JO LPO fields
  subcontractor_id?: number;
  subcontractor_name?: string;
  subcontractor_trn_number?: string;
  subcontractor_address?: string;
  subcontractor_contact_person?: string;
  subcontractor_email?: string;
  lpo_jo_lines?: LPOJoLine[];
};
