export type MrHeader = {
  mrHeader: number;
  id: number;
  type: "material" | "job" | "payment";
  project_id: number;
  project_name: string;
  department_id: number;
  department_name: string;
  requested_by: string;
  required_date: string;
  priority: string;
  purpose_id: number;
  purpose_name: string;
  progress_id: number;
  progress_name: string;
  date_requested: string;
  delivery_date: string;
  jo_invoice_file: string;
  jo_payment_receipt: string;
  jo_contract_file: string | null;
  jo_other_docs_file: string | null;
  payment_jo_reference_id?: number | null;
  pr_payment_receipt?: string | null;
  item_count?: number;
  identifier?: string | null;
  skip_approvals?: number | null;
};
