export type MrLine = {
  id: number;
  project_id: number;
  project_name: string;
  mr_header_id: number;
  material_category_id: number;
  material_category: string;
  material_subcategory_id: string | number | number[];
  material_subcategory: string;
  material_description: string;
  quantity: number;
  unit: string;
  notes: string;
  specification: string;
  brand: string;
  attachment: string;
  delivery_location: string;
  boq_header_id: number;
  boq_line_ids: string;
  boq_line_id: number;
  boq_item_name: string;
  boq_item_number: string;
  boq_item_description: string;
  boq_scope_of_work: string;
  boq_quantity: number;
  boq_unit: string;
  boq_category: string;
  boq_sub_category: string;
  boq_location: string;
  boq_rate: number;
  boq_total_cost: number;
  boq_attachments: string[];
  approval_status: string;
  reject_comment: string;
  qs_approval_status: string;
  qs_reject_comment: string;
  qs_review_type: "item_available" | "need_order" | null;
  linked_inventory_item_id: number | null;
  linked_inventory_item_description: string | null;
  stock_transfer_id: number | null;
  signed_dn_file: string | null;
  approved_supplier_id: number;
  approved_supplier_type: string;
  approved_supplier_name: string;
  approved_unit_price: number;
  approved_total_price: number;
  approved_proposed_quantity: number;
  approved_supplier_material_categories: string;
  approved_supplier_material_subcategories: string;
  approved_supplier_avg_lead_time: string;
  approved_supplier_rating: number;
  approved_supplier_trn_number: string;
  approved_supplier_contact_person: string;
  approved_supplier_phone: string;
  approved_supplier_email: string;
  approved_supplier_address: string;
  approved_vat_rate: number;
  stock_inventory_item_id: number | null;
  stock_inventory_item_name: string | null;
};
